services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=n8n.${BASE_HOSTNAME:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.${BASE_HOSTNAME:-localhost}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/London}
      - TZ=${GENERIC_TIMEZONE:-Europe/London}
    volumes:
      - n8n_data:/home/node/.n8n
    deploy:
      restart_policy:
        condition: unless-stopped
    networks:
      - proxy_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_proxy"
      # http
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${BASE_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
      - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
      # https
      - "traefik.http.routers.n8n-secure.entrypoints=websecure"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.${BASE_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.n8n-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.n8n-secure.service=n8n-secure"
      - "traefik.http.services.n8n-secure.loadbalancer.server.port=5678"
      - "deunhealth.restart.on.unhealthy=true"

volumes:
  n8n_data:

networks:
  proxy_proxy:
    external: true