services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.0.2 #
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1000M #
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      BASE_URL: https://recipes.${BASE_HOSTNAME:-localhost}
    networks:
      - proxy_proxy
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.mealie.entrypoints=web"
      - "traefik.http.routers.mealie.rule=Host(`recipes.${BASE_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.mealie.middlewares=mealie-https-redirect"
      - "traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme=https"
      # https
      - "traefik.http.routers.mealie-secure.entrypoints=websecure"
      - "traefik.http.routers.mealie-secure.rule=Host(`recipes.${BASE_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.mealie-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.mealie-secure.service=mealie-secure"
      - "traefik.http.services.mealie-secure.loadbalancer.server.port=9000"

volumes:
  mealie-data:

networks:
  proxy_proxy:
    external: true
